# Generated by Django 3.2.4 on 2021-06-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordis_app', '0002_spotifytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
