# Generated by Django 3.2.4 on 2021-06-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordis_app', '0003_alter_spotifytoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
