# Generated by Django 3.2.4 on 2021-06-10 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordis_app', '0004_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_user', to='recordis_app.spotifytoken'),
        ),
    ]
